### ISSUE TITLE
Some clean up questions

### ISSUE THREAD

**Issue by dan800** [jack-eddy-symposium/exoplanetary-impact#3]
@G-J-Cooke Can the duplicated json files that are capitalized be deleted. Also, which is *the* SWIM notebook - the Stellar_spectra_conversion or Stellar_Wind_and_Irradiance_Module? It's confusing to have both. We might want to create a SWIM subdirectory since there's a mix in here of meeting notes, example notebooks, etc.

**Comment by cookehmh** [comment]
The Stellar_Wind_and_Irradiance_Module is the SWIM notebook. Sounds good to me.

**Comment by colliand** [comment]
Is this issue completed? Should it be closed? @dan800 @cookehmh

**Comment by dan800** [comment]
I think so. Greg?

**Comment by cookehmh** [comment]
Yes all good
